spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888

#welcome: "Hello Vinh"

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttempts: 3
        waitDuration: 9s

  ratelimiter:
    instances:
      # RateLimiter object used in RateLimitingService.basicExample()
      basicExample:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 10s
